# Generated by Django 3.2.11 on 2022-11-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20221104_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentquestion',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='essayquestion',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='objectivequestion',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
