# Generated by Django 3.2.11 on 2022-11-06 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_batch_live'),
        ('student', '0001_initial'),
        ('exam', '0003_auto_20221104_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCompletedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.PositiveIntegerField(choices=[(0, 'Initial'), (1, 'Complete Get'), (2, 'Complete Post')], default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.batch')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
