# Generated by Django 3.2.11 on 2023-07-24 13:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacher_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='lga_of_origin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='LGA of origin'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='nationality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
