# Generated by Django 3.2.11 on 2022-10-26 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('downloadable', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to='product/file')),
                ('image', models.ImageField(upload_to='product/image')),
                ('price', models.PositiveIntegerField(help_text='Price in Naira')),
                ('is_free', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
