# Generated by Django 3.2.11 on 2022-10-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='live',
            field=models.BooleanField(default=True, help_text='Unless marked, product will be visible to students'),
        ),
    ]
