# Generated by Django 3.2.11 on 2022-10-17 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
        ('academic', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcompletedmodule',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models_completed', to='student.student'),
        ),
        migrations.AddField(
            model_name='studentcompletedcourse',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.batch'),
        ),
        migrations.AddField(
            model_name='studentcompletedcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_completed_course', to='course.course'),
        ),
        migrations.AddField(
            model_name='studentcompletedcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couses_completed', to='student.student'),
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='course.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_to_take', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses_joined', to='student.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='course.subject'),
        ),
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('text', 'video', 'image', 'file')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='content',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='course.module'),
        ),
        migrations.AlterUniqueTogether(
            name='studentcompletedmodule',
            unique_together={('student', 'module', 'batch')},
        ),
        migrations.AlterUniqueTogether(
            name='studentcompletedcourse',
            unique_together={('student', 'course', 'batch')},
        ),
    ]
