# Generated by Django 3.2.11 on 2022-11-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20221026_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='certificate_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Enrollment price'),
        ),
    ]
