# Generated by Django 3.2.11 on 2022-11-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20221103_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='live',
            field=models.BooleanField(default=False),
        ),
    ]
