# Generated by Django 3.2.11 on 2022-11-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_content_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exam_open',
            field=models.BooleanField(default=False, help_text='Unless marked, Students can not take Exam related to this Course'),
        ),
    ]
