# Generated by Django 3.2.11 on 2022-10-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Batch A', max_length=100)),
                ('order', models.PositiveSmallIntegerField(blank=True, help_text='eg 1 for Batch A', null=True, unique=True)),
                ('is_current', models.BooleanField(default=False, editable=False, help_text='When set to current, the current term will be overwritten')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
