# Generated by Django 3.2.11 on 2022-11-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='live',
            field=models.BooleanField(default=False, help_text='Unless marked, Students can perform many activities in this batch'),
        ),
    ]
