# Generated by Django 3.2.11 on 2022-11-09 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_batch_live'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='batch',
            name='next_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.batch'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='live',
            field=models.BooleanField(default=False, help_text='Unless marked, Students can perform some activities in this batch'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(help_text='Batch A', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, help_text='eg 1 for Batch A', null=True),
        ),
    ]
