# Generated by Django 3.2.11 on 2022-11-08 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('result', '0006_auto_20221107_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='certificate')),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='result.studentresult')),
            ],
        ),
    ]
