"""
Django settings for oelern project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True #config('DEBUG')

ALLOWED_HOSTS = ['127.0.0.1',]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    'phonenumber_field',
    'intl_tel_input',
    'bootstrap_datepicker_plus',
    'bootstrap4',
    'django_tables2',
    'widget_tweaks',
    'embed_video',
    'jquery',
    'djangoformsetjs',

    'paystack.apps.PaystackConfig',

    'custom_auth.apps.CustomAuthConfig',
    'student.apps.StudentConfig',
    'student_reg.apps.StudentRegConfig',
    'academic.apps.AcademicConfig',
    'payment.apps.PaymentConfig',
    'teacher.apps.TeacherConfig',
    'course.apps.CourseConfig',
    'exam.apps.ExamConfig',
    'result.apps.ResultConfig',
    'product.apps.ProductConfig',
    'certificate.apps.CertificateConfig',

    'dashboard.apps.DashboardConfig',
    'dashboard.teacher.apps.TeacherDashboardConfig',
    'dashboard.course.apps.CourseDashboardConfig',
    'dashboard.exam.apps.ExamDashboardConfig',
    'dashboard.product.apps.ProductDashboardConfig',
    'dashboard.custom_auth.apps.CustomAuthDashboardConfig',
    'dashboard.result.apps.ResultDashboardConfig',
    'dashboard.certificate.apps.CertificateDashboardConfig',
    'dashboard.academic.apps.AcademicDashboardConfig',
    'dashboard.student.apps.StudentDashboardConfig',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'oelern.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'academic.context_processors.get_current_batch_to_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'oelern.wsgi.application'

# Database

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_L10N = True

USE_TZ = True

#paystack payment gateway
PAYSTACK_SUCCESS_URL = '/student'
PAYSTACK_PUBLIC_KEY =  config('PAYSTACK_PUBLIC_KEY')
PAYSTACK_SECRET_KEY =  config('PAYSTACK_SECRET_KEY')
PAYSTACK_WEBHOOK_DOMAIN = config('PAYSTACK_WEBHOOK_DOMAIN')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

#APPEND_SLASH=False

#ATOMIC_REQUESTS = False
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static_files') #'/home/alhudaa1/alhudaacademy.com.ng/static_files'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'static_media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' #'django.core.mail.smtp.EmailBackend'
#IT IS NOT REQUIRED IN THIS PROJECT
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_USE_TLS = config('EMAIL_USE_TLS')
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

AUTH_USER_MODEL = 'custom_auth.CustomUser'

LOGIN_URL = '/auth/login/'

LOGIN_REDIRECT_URL = '/redirect'

LOGOUT_REDIRECT_URL = '/auth/login'

PHONENUMBER_DB_FORMAT = 'E164'

SCHOOL_NAME = 'ONLINE ENGLISH LEARNIG SCHOOL'

#Django tables items in a single table page

TABLE_ROWS_PER_PAGE = 20

#Result

CA_MARK_ALLOCATION = 30
EXAM_MARK_ALLOCATION = 70

TABLE_ROWS_PER_PAGE = 10

MAX_CA_SCORE = 30

MAX_EXAM_SCORE = 70

MAX_TOTAL_SCORE = MAX_CA_SCORE + MAX_EXAM_SCORE