# Generated by Django 3.2.11 on 2022-11-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20221109_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.ImageField(default='media/default.jpg', upload_to='student'),
            preserve_default=False,
        ),
    ]
