# Generated by Django 3.2.11 on 2022-11-22 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_auto_20221109_0424'),
        ('student', '0003_alter_student_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='start_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.batch'),
        ),
    ]
