# Generated by Django 3.2.11 on 2022-12-10 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_start_batch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-date_joint']},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='created',
            new_name='date_joint',
        ),
    ]
